(function(){
  const d=document, header=d.querySelector('.site-header'), toggle=d.querySelector('.menu-toggle'), menu=d.querySelector('.mobile-menu'), sheet=d.querySelector('.booking-sheet'), backdrop=d.querySelector('.sheet-backdrop'), close=d.querySelectorAll('[data-close-sheet]');
  const page=location.pathname.match(/natural-birth|normal-vaginal-delivery|vbac-consultation|pregnancy-antenatal-care/)?.[0]||'pregnancy-antenatal-care';
   const data={
     'pregnancy-antenatal-care':{intentTitle:'You may be here because…',intent:['You have recently found out you are pregnant.','You are looking for ongoing antenatal care.','You want birth preparation to begin during pregnancy.','You are considering changing your pregnancy-care provider.'],proof:'Pregnancy, continuity and clear next steps',doctor:'Pregnancy care that keeps the whole journey in view.',gallery:'Pregnancy care in action',galleryCaptions:['Preparing together','Understanding labour','Movement during pregnancy','Questions welcomed'],topics:['When should I schedule my first antenatal appointment?','When should I start preparing for birth?','What does holistic pregnancy care include?'],links:[['Natural Birth','natural-birth.html'],['Normal Delivery','normal-vaginal-delivery.html'],['VBAC','vbac-consultation.html']],service:'Pregnancy & Antenatal Care'},
     'natural-birth':{intentTitle:'Is natural birth what you are looking for?',intent:['You want to understand what natural birth actually means.','You want to prepare before labour begins.','You want to explore breathing, movement and lower-intervention labour where appropriate.','You want your birth partner involved.'],proof:'Preparation, informed choices and calm conversations',doctor:'A conversation that makes room for preferences and clinical context.',gallery:'Preparing together',galleryCaptions:['Breathing together','Movement for labour','Birth-partner education','Questions welcomed'],topics:['Natural birth vs normal vaginal delivery','Preparing for labour with breathing and movement','When should natural-birth preparation begin?'],links:[['Pregnancy Care','pregnancy-antenatal-care.html'],['Normal Delivery','normal-vaginal-delivery.html'],['VBAC','vbac-consultation.html']],service:'Natural Birth'},
     'normal-vaginal-delivery':{intentTitle:'You may be here because…',intent:['You are hoping to prepare for vaginal birth.','You want to understand labour before it begins.','You want to discuss movement, pain relief and birth preferences.','You want realistic guidance without promises.'],proof:'Preparation, communication and responsive care',doctor:'Support for vaginal birth that stays grounded in individual needs.',gallery:'Birth preparation in action',galleryCaptions:['Understanding labour','Preparing with a partner','Comfort and movement','Questions welcomed'],topics:['Understanding the stages of labour','Pain-relief and comfort options during labour','Why birth plans sometimes need to change'],links:[['Pregnancy Care','pregnancy-antenatal-care.html'],['Natural Birth','natural-birth.html'],['VBAC','vbac-consultation.html']],service:'Normal Vaginal Delivery'},
     'vbac-consultation':{intentTitle:'You may be here because…',intent:['You had a previous Caesarean.','You want to know whether vaginal birth may be an option this time.','You have previous delivery records but do not know what matters.','You want your history reviewed individually.'],proof:'A careful review, not a promise',doctor:'A VBAC conversation begins with your history and current pregnancy.',gallery:'Questions welcomed',galleryCaptions:['A history worth hearing','Reviewing your records','Planning with care','Questions welcomed'],topics:['Can I consider vaginal birth after one Caesarean?','What previous records should I bring?','When should VBAC conversations begin?','Why might a VBAC plan change?'],links:[['Pregnancy Care','pregnancy-antenatal-care.html'],['Normal Delivery','normal-vaginal-delivery.html'],['Natural Birth','natural-birth.html']],service:'VBAC Consultation'}
   }[page];
    d.body.classList.add(`page-${page}`);
    d.querySelectorAll('.brand').forEach(brand=>{if(!brand.querySelector('.brand-logo')){brand.insertAdjacentHTML('afterbegin','<img class="brand-logo" src="assets/birthwave-logo.png" alt="The Birthwave">');brand.setAttribute('aria-label','The Birthwave by Dr. Santoshini Nandigam')}});
   function replaceUnapprovedMedia(){
     const media={main:'assets/dr-santoshini.jpg',side:'assets/clinic-detail.jpg',editorial:'assets/clinic-exterior.jpg'};
     d.querySelectorAll('img[src*="images.unsplash.com"]').forEach(img=>{
       const file=img.classList.contains('hero-main')?media.main:img.classList.contains('hero-side')?media.side:media.editorial;
       img.src=file;
       if(img.classList.contains('hero-main'))img.alt='Dr. Santoshini Nandigam at Birthwave';
       else if(img.classList.contains('hero-side'))img.alt='The Birthwave clinic interior';
       else img.alt='The Birthwave clinic in Nungambakkam';
     });
    const copy=d.querySelector('.hero-copy');
    if(copy&&!copy.querySelector('.hero-trust'))copy.insertAdjacentHTML('beforeend','<div class="hero-trust"><span>Doctor-led care</span><span>Pregnancy → birth → recovery</span><span>Nungambakkam, Chennai</span></div>');
  }
  function injectFunnel(){
    const faq=d.querySelector('#faq'); if(!faq||d.querySelector('.conversion-layer'))return;
      const placeholder=(label,kind='photo')=>{const files={workshop:'assets/clinic-detail.jpg',programme:'assets/clinic-exterior.jpg',session:'assets/dr-santoshini.jpg',consultation:'assets/clinic-detail.jpg'};return `<div class="media-placeholder real-media ${kind}" role="img" aria-label="${label}" style="background-image:url('${files[kind]||files.workshop}')"><span>Birthwave</span><strong>${label}</strong></div>`};
    const links=data.links.map(([label,href])=>`<a href="${href}">${label} <span class="arrow">→</span></a>`).join('');
    const intents=data.intent.map(item=>`<div class="intent-item">${item}</div>`).join('');
     const topics=data.topics.map((item,i)=>`<article class="learn-card ${i===0?'featured':''}"><small>${i===0?'Featured resource':'Learn with Dr. Santoshi'}</small><h3 class="display">${item}</h3><p>Approved Birthwave article or video to be linked here.</p><a href="#book">Watch / Read <span class="arrow">→</span></a></article>`).join('');
    const html=`<div class="conversion-layer" data-od-id="conversion-funnel">
      <section class="intent-section" data-od-id="patient-intent"><div class="container intent-wrap"><div><p class="eyebrow">A familiar starting point</p><h2 class="display">${data.intentTitle}</h2></div><div><p>Many people arrive with questions rather than a complete plan. Birthwave is a place to begin the conversation.</p><div class="intent-list">${intents}</div></div></div></section>
       <section class="proof-section" data-od-id="patient-experiences"><div class="container"><div class="proof-head"><div><p class="eyebrow">Stay connected</p><h2 class="display">${data.proof}</h2></div><p>Follow Birthwave for clinic updates, care education and moments from the team.</p></div><div class="proof-grid"><article class="proof-card"><blockquote>Care stories, education and clinic moments.</blockquote><small>Instagram · @birthtoremember</small><a class="text-link" href="https://www.instagram.com/birthtoremember/" target="_blank" rel="noreferrer">Follow on Instagram →</a></article><article class="proof-card"><blockquote>Longer conversations about pregnancy and birth.</blockquote><small>YouTube · Birth to Remember</small><a class="text-link" href="https://www.youtube.com/@birthtoremember" target="_blank" rel="noreferrer">Watch on YouTube →</a></article><article class="proof-card"><blockquote>Bring your questions to a direct consultation.</blockquote><small>The Birthwave · Nungambakkam, Chennai</small><a class="text-link" href="#book" data-book>Start a conversation →</a></article></div></div></section>
       <section class="doctor-section" data-od-id="doctor-anchor"><div class="container doctor-layout"><div class="doctor-photo doctor-photo-placeholder real-media" role="img" aria-label="Dr. Santoshini Nandigam at Birthwave" style="background-image:url('assets/dr-santoshini.jpg')"><span>Birthwave clinical team</span><strong>Dr. Santoshini Nandigam</strong></div><div class="doctor-copy"><p class="eyebrow">Meet your clinical anchor</p><h2 class="display">${data.doctor}</h2><span class="doctor-role">Dr. Santoshini Nandigam · Founder · Obstetrician &amp; Gynaecologist</span><p>Good care starts with being heard. Bring your questions, history and preferences into a direct conversation about what may be appropriate for you.</p><div class="doctor-points"><span>Doctor-led conversations</span><span>Questions welcomed</span><span>Care connected across stages</span><span>Individual clinical context</span></div><a class="btn btn-primary" href="#book" data-book>Book with Dr. Santoshi <span class="arrow">→</span></a></div></div></section>
       <section class="action-section compact-action" data-od-id="doctor-cta"><div class="container action-head"><div><p class="eyebrow">A useful next step</p><h2 class="display">Have questions about your care plan?</h2></div><div class="action-buttons"><a class="btn btn-primary" href="#book" data-book>Book a consultation <span class="arrow">→</span></a><a class="text-link" href="https://wa.me/919363031925">WhatsApp Birthwave <span class="arrow">→</span></a></div></div></section>
      <section class="action-section" data-od-id="trust-reasons"><div class="container"><div class="action-head"><div><p class="eyebrow">Why women start a conversation here</p><h2 class="display">Support that stays human.</h2></div><p>Clear explanations and connected support can make a complex journey feel more navigable.</p></div><div class="action-grid"><article class="action-card"><h3 class="display">Birth preparation begins during pregnancy.</h3><p>The conversation does not have to start in the labour room.</p></article><article class="action-card"><h3 class="display">Care beyond one appointment.</h3><p>Pregnancy, preparation, recovery and newborn care can remain connected.</p></article><article class="action-card"><h3 class="display">Questions are part of care.</h3><p>Understand why something is being recommended and what to ask next.</p></article><article class="action-card"><h3 class="display">Support around medical care.</h3><p>Nutrition, movement, education and other supportive services can connect where appropriate.</p></article></div></div></section>
        <section class="gallery-section" data-od-id="birthwave-in-action"><div class="container"><div class="section-head"><div><p class="eyebrow">Birthwave in action</p><h2 class="display">${data.gallery}</h2></div><p>See the clinic, the care environment and the people who make space for your questions.</p></div><div class="gallery-grid"><figure>${placeholder(data.galleryCaptions[0],'workshop')}<figcaption>${data.galleryCaptions[0]}</figcaption></figure><figure>${placeholder(data.galleryCaptions[1],'programme')}<figcaption>${data.galleryCaptions[1]}</figcaption></figure><figure>${placeholder(data.galleryCaptions[2],'session')}<figcaption>${data.galleryCaptions[2]}</figcaption></figure><figure>${placeholder(data.galleryCaptions[3],'consultation')}<figcaption>${data.galleryCaptions[3]}</figcaption></figure></div><p class="media-note">Photography from The Birthwave clinic and care team.</p></div></section>
       <section class="action-section compact-action" data-od-id="gallery-cta"><div class="container action-head"><div><p class="eyebrow">Seen enough to ask a question?</p><h2 class="display">Want to understand what support may be right for you?</h2></div><a class="btn btn-primary" href="#book" data-book>Talk to the Birthwave team <span class="arrow">→</span></a></div></section>
       <section class="learn-section" data-od-id="learn-with-santoshi"><div class="container"><div class="learn-head"><div><p class="eyebrow">Learn with Dr. Santoshi</p><h2 class="display">Bring clearer questions to your next visit.</h2></div><p>Relevant articles and videos should open approved Birthwave content, not an unrelated library.</p></div><div class="learn-grid">${topics}</div><div class="context-links">${links}</div></div></section>
        <section class="clinic-section" data-od-id="visit-birthwave"><div class="container clinic-grid"><div><p class="eyebrow">Visit Birthwave</p><h2 class="display">A real place to continue the conversation.</h2><p class="clinic-name">The Birthwave Gynecology and Children’s Clinic</p><p class="address">8/15, Mahalingapuram Main Rd, Mahalingapuram, Nungambakkam, Chennai, Tamil Nadu 600034</p><p><a href="tel:+919363031925">+91 93630 31925</a></p><div class="clinic-actions"><a class="btn btn-primary" href="https://maps.google.com/?q=The+Birthwave+Gynecology+and+Children%27s+Clinic+Nungambakkam+Chennai" target="_blank" rel="noreferrer">Get Directions <span class="arrow">→</span></a><a class="text-link" href="https://wa.me/919363031925">WhatsApp <span class="arrow">→</span></a></div></div><div class="map-placeholder real-media" role="img" aria-label="The Birthwave clinic exterior" style="background-image:url('assets/clinic-exterior.jpg')"><span>Birthwave clinic</span><strong>Nungambakkam, Chennai</strong></div></div></section>
    </div>`;
     faq.insertAdjacentHTML('beforebegin',html);
      d.querySelector('.gallery-section .container')?.insertAdjacentHTML('beforeend','<div class="care-video"><div><p class="eyebrow">A quieter look at Birthwave</p><h2 class="display">See the care environment before you visit.</h2><p>Take a short look at the clinic and the team’s care-led approach.</p></div><video controls preload="metadata" poster="assets/clinic-exterior.jpg"><source src="assets/birthwave-care-optimized.mp4" type="video/mp4">Your browser does not support video playback.</video></div>');
  }
  replaceUnapprovedMedia();
   injectFunnel();
  function closeMenu(){if(!menu)return;menu.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}
  toggle?.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
   function bindForm(form){if(!form)return; if(!form.querySelector('input[name="service"]')){const service=d.createElement('input');service.type='hidden';service.name='service';service.value=data.service;form.appendChild(service)} /* TODO: Connect consultation form to Birthwave lead endpoint / CRM. */ form.addEventListener('submit',e=>{e.preventDefault();const status=form.querySelector('.form-status');if(status){form.querySelectorAll('.field,.form-note,.btn').forEach(el=>el.style.display='none');status.classList.add('show')}})}
  function openSheet(){if(sheet&&!sheet.querySelector('.sheet-form')){const source=d.querySelector('form.mini-form');if(source){const clone=source.cloneNode(true);clone.classList.add('sheet-form');clone.removeAttribute('id');clone.querySelectorAll('[id]').forEach(field=>{const next=`sheet-${field.id}`;clone.querySelectorAll(`label[for="${field.id}"]`).forEach(label=>label.setAttribute('for',next));field.id=next});sheet.appendChild(clone);bindForm(clone)}}sheet?.classList.add('open');backdrop?.classList.add('show');document.body.classList.add('sheet-open');sheet?.querySelector('.sheet-form input')?.focus()}
  function closeSheet(){sheet?.classList.remove('open');backdrop?.classList.remove('show');document.body.classList.remove('sheet-open')}
  d.querySelectorAll('[data-book]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openSheet()}));close.forEach(a=>a.addEventListener('click',closeSheet));backdrop?.addEventListener('click',closeSheet);d.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSheet();closeMenu()}});
  window.addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>35),{passive:true});
  d.querySelectorAll('.faq-q').forEach(q=>q.addEventListener('click',()=>{const item=q.parentElement;const was=item.classList.contains('open');d.querySelectorAll('.faq-item').forEach(i=>{i.classList.remove('open');i.querySelector('.faq-q').setAttribute('aria-expanded','false')});if(!was){item.classList.add('open');q.setAttribute('aria-expanded','true')}}));
  d.querySelectorAll('form').forEach(bindForm);
})();
